#!/usr/bin/env bash

 HIGH="1995us"
  LOW="995us"
 SYNC="2995us"
PAUSE="995us"
  END="0"

((payload = ((16#"$1") << 8) + (16#"$2") ))

bits=16

timestr="$SYNC,$PAUSE"

while ((bits-- > 0))
do
  ((payload & 16#8000)) && downtime="$HIGH" || downtime="$LOW"
  ((payload = payload << 1))
  timestr="$timestr,$downtime,$PAUSE"
done

timestr="${timestr%,*},$END"
#printf "%08d %08d\n" "$byte1" "$byte2"
chrt 11 gpioset -c 0 -t "$timestr" 24=0
