#!/usr/bin/env bash

((
  MSG_NONE                  = 16#00,
  MSG_SYS_POWEROFF          = 16#02,
  MSG_BOOTUP                = 16#04,
  MSG_SHUTDOWN_GUARD        = 16#06,
  MSG_POWER_STATE           = 16#08,
  MSG_POWER_VOLTAGE_VALUE   = 16#0A,
  MSG_BATTERY_VOLTAGE_VALUE = 16#0C,

  MSG_POWER_VOLTAGE_NOMINAL = 16#10,
  MSG_POWER_VOLTAGE_MIN     = 16#12,
  MSG_CAPACITOR_VOLTAGE_MIN = 16#14,
  MSG_SWITCHING_VOLTAGE_MIN = 16#16,
  MSG_BATTERY_VOLTAGE_MIN   = 16#18,
  MSG_BATTERY_VERSION       = 16#1A,
  MSG_PORT_POWEROFF         = 16#1C,
  MSG_SWITCHING_TIMEOUT     = 16#1E,

  MSG_CMD_MASK              = 16#3E000000,
  MSG_DATA_MASK             = 16#01FFFFFF,
  MSG_WRITE_MASK            = 16#80000000
))

STATE_DIR=/run/wp360-ups-ctrl

mkdir -p "${STATE_DIR}"

interface_write()
{
  echo "$2" > "${STATE_DIR}/$1"
}

parse_command()
{
  local  cmd=$(( ($1 & MSG_CMD_MASK)  >> $2 ))
  local data=$(( ($1 & MSG_DATA_MASK) >> $2 ))
 
  case "$cmd" in
    "$MSG_POWER_STATE")
      interface_write PowerState "$data"
      ;;
    "$MSG_POWER_VOLTAGE_VALUE")
      interface_write PowerVoltageValue "$data"
      ;;
    "$MSG_BATTERY_VOLTAGE_VALUE")
      interface_write BatteryVoltageValue "$data"
      ;;
    "$MSG_POWER_VOLTAGE_NOMINAL")
      interface_write PowerVoltageNominal "$data"
      ;;
    "$MSG_POWER_VOLTAGE_MIN")
      interface_write PowerVoltageMin "$data"
      ;;
    "$MSG_CAPACITOR_VOLTAGE_MIN")
      interface_write CapacitorVoltageMin "$data"
      ;;
   "$MSG_SWITCHIMG_VOLTAGE_MIN")
      interface_write SwitchingVoltageMin "$data"
      ;;
   "$MSG_BATTERY_VOLTAGE_MIN")
      interface_write BatteryVoltageMin "$data"
      ;;
    "$MSG_BATTERY_VERSION")
      interface_write BatteryVersion "$data"
      ;;
    "$MSG_PORT_POWEROFF")
      interface_write PortPoweroff "$data"
      ;;
    "$MSG_SWITCHING_TIMEOUT")
      interface_write SwitchingTimeout "$data"
      ;;
  esac
}

while read evtime state
do
  evtime="${evtime//.}"
  case "$state" in
    1) # rising, end of bit
      dt=$(( (evtime - lastTime + 500000) / 100000 )) # low pulse length, round to nearest decimillisec
      if (( dt >= 7 && dt <= 13 && bits > 0 ))
      then
        ((
        payload = payload << 1,
        bits--
        ))
      elif (( dt >= 17 && dt <= 13 && bits > 0 ))
      then
        ((
        payload = (payload << 1) + 1,
        bits--
        ))
      elif (( dt >= 27 && dt <= 33 ))
      then
        ((
        payload = 0,
        bits = 8,
        shift = 1
        ))
      elif (( dt >= 37 && dt <= 43 ))
      then
        ((
        payload = 0,
        bits = 16,
        shift = 16
        ))
      elif (( dt >= 47 && dt <= 53 ))
      then
        ((
        payload = 0,
        bits = 32,
        shift = 0
        ))
      else
        ((
        bits = -1
        ))
      fi

      if (( bits == 0 ))
      then
        (( payload = payload << shift ))
        parse_command "$payload" "$shift"
        printf "Command: 0x%X\n" "$payload"
        # :
      fi
      ;;
    2) # falling, start of bit
      lastTime="$evtime"
      ;;
  esac
done < <(chrt 11 gpiomon -c 0 -F "%S %e" -E realtime 23)
