#!/bin/sh
PREREQ=""
prereqs()
{
  echo "$PREREQ"
}
case $1 in
prereqs)
  prereqs
  exit 0
;;
esac

. /scripts/functions
# Begin real processing below this line
gpioset --bias=pull-down --drive=push-pull -c 0 -t 5,0 24=1
