#!/bin/sh
PREREQ=""
prereqs()
{
echo "$PREREQ"
}
case $1 in
prereqs)
  prereqs
  exit 0
;;
esac

. /usr/share/initramfs-tools/hook-functions
# Begin real processing below this line
force_load gpio_keys
copy_exec $(which gpioset)
